// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 17.0.0.0
//
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DataTables.GeneratorCore
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;

    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class DataMatrixTemplate : DataMatrixTemplateBase
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"// <auto-generated />
#pragma warning disable CS0105
#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring as nullable.
#pragma warning disable CS8602 // Dereference of a possibly null reference.
using System;
using System.IO;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using DataTables;

#nullable enable

");
 if (!string.IsNullOrEmpty(GenerationContext.Namespace)) {
            this.Write("namespace ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.Namespace));
            this.Write("\r\n{\r\n");
 }
            this.Write("\r\npublic sealed partial class DT");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.ClassName));
            this.Write(" : DataMatrixBase<");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kKey1)));
            this.Write(", ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kKey2)));
            this.Write(", ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kValue)));
            this.Write(">\r\n{\r\n    public override ulong SchemaHash => ");
            this.Write(this.ToStringHelper.ToStringWithCulture(DataTableSchemaHash.Compute(GenerationContext)));
            this.Write("UL;\r\n\r\n    ");
            this.Write(this.ToStringHelper.ToStringWithCulture(string.IsNullOrEmpty(GenerationContext.MatrixDefaultValue) ? string.Empty : "protected override " + BuildTypeString(kValue) + " DefaultValue => " + BuildTypeValueString(kValue, GenerationContext.MatrixDefaultValue) + ";" + Environment.NewLine));
            this.Write("\r\n    public DT");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.ClassName));
            this.Write("(string name, int capacity) : base(name, capacity)\r\n    { }\r\n\r\n    public overrid" +
                    "e bool ParseDataRow(int index, BinaryReader reader)\r\n    {\r\n        ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kKey1)));
            this.Write(" ");
            this.Write(this.ToStringHelper.ToStringWithCulture(kKey1));
            this.Write(";\r\n        ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildDeserializeMethodString(kKey1)));
            this.Write("\r\n\r\n        ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kKey2)));
            this.Write(" ");
            this.Write(this.ToStringHelper.ToStringWithCulture(kKey2));
            this.Write(";\r\n        ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildDeserializeMethodString(kKey2)));
            this.Write("\r\n\r\n        ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kValue)));
            this.Write(" ");
            this.Write(this.ToStringHelper.ToStringWithCulture(kValue));
            this.Write(";\r\n        ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildDeserializeMethodString(kValue)));
            this.Write("\r\n\r\n        SetDataRow(index, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(kKey1));
            this.Write(", ");
            this.Write(this.ToStringHelper.ToStringWithCulture(kKey2));
            this.Write(", ");
            this.Write(this.ToStringHelper.ToStringWithCulture(kValue));
            this.Write(");\r\n        return true;\r\n    }\r\n\r\n    #region Instance API\r\n\r\n    /// <summary>\r" +
                    "\n    /// 根据Key1和Key2获取数据值 (实例方法)\r\n    /// </summary>\r\n    [MethodImpl(MethodImpl" +
                    "Options.AggressiveInlining)]\r\n    public ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kValue)));
            this.Write("? GetDataRow(");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kKey1)));
            this.Write(" key1, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kKey2)));
            this.Write(" key2)\r\n    {\r\n        return Get(key1, key2);\r\n    }\r\n\r\n    /// <summary>\r\n    /" +
                    "// 根据Key1和Key2获取数据值，如果不存在则返回默认值 (实例方法)\r\n    /// </summary>\r\n    [MethodImpl(Meth" +
                    "odImplOptions.AggressiveInlining)]\r\n    public ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kValue)));
            this.Write(" GetDataRowOrDefault(");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kKey1)));
            this.Write(" key1, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kKey2)));
            this.Write(" key2)\r\n    {\r\n        return Get(key1, key2)!;\r\n    }\r\n\r\n    #endregion\r\n\r\n    #" +
                    "region Static API\n\n    /// <summary>\n    /// 获取数据矩阵实例 - 便于访问基类方法 (静态方法)\n    /// " +
                    "</summary>\n    public static DT");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.ClassName));
            this.Write(" GetTable(DataTableContext context) => GetTable(context, string.Empty);\n\n    publ" +
                    "ic static DT");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.ClassName));
            this.Write(" GetTable(DataTableContext context, string dataTableName)\n    {\n        var table" +
                    " = context.GetCached<DT");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.ClassName));
            this.Write(">(dataTableName);\n        if (table == null)\n        {\n            throw new Inva" +
                    "lidOperationException($\"DT");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.ClassName));
            this.Write(" \'{dataTableName}\' is not loaded. Call context.LoadAsync<DT");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.ClassName));
            this.Write(">(dataTableName) first.\");\n        }\n        return table;\n    }\r\n\r\n    /// <summ" +
                    "ary>\n    /// 安全获取数据矩阵实例 - 返回null如果未加载 (静态方法)\n    /// </summary>\n    public stati" +
                    "c DT");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.ClassName));
            this.Write("? GetTableOrNull(DataTableContext context) => GetTableOrNull(context, string.Empt" +
                    "y);\n\n    public static DT");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.ClassName));
            this.Write("? GetTableOrNull(DataTableContext context, string dataTableName) => context.GetCa" +
                    "ched<DT");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.ClassName));
            this.Write(@">(dataTableName);

    /// <summary>
    /// 检查数据矩阵是否已加载 (静态方法)
    /// </summary>
    public static bool IsLoaded(DataTableContext context) => IsLoaded(context, string.Empty);

    public static bool IsLoaded(DataTableContext context, string dataTableName) => context.IsLoaded<DT");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.ClassName));
            this.Write(">(dataTableName);\n\r\n    /// <summary>\r\n    /// 根据Key1和Key2获取数据值 (静态方法)\r\n    /// <" +
                    "/summary>\r\n    [MethodImpl(MethodImplOptions.AggressiveInlining)]\r\n    public st" +
                    "atic ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kValue)));
            this.Write("? GetRow(DataTableContext context, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kKey1)));
            this.Write(" key1, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kKey2)));
            this.Write(" key2) => GetRow(context, string.Empty, key1, key2);\n\n    [MethodImpl(MethodImplO" +
                    "ptions.AggressiveInlining)]\n    public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kValue)));
            this.Write("? GetRow(DataTableContext context, string dataTableName, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kKey1)));
            this.Write(" key1, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kKey2)));
            this.Write(" key2)\n    {\n        var table = context.GetCached<DT");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.ClassName));
            this.Write(">(dataTableName);\n        return table?.Get(key1, key2);\n    }\r\n\r\n    /// <summar" +
                    "y>\r\n    /// 根据Key1和Key2获取数据值，如果不存在则返回默认值 (静态方法)\r\n    /// </summary>\r\n    [Method" +
                    "Impl(MethodImplOptions.AggressiveInlining)]\r\n    public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kValue)));
            this.Write(" GetRowOrDefault(DataTableContext context, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kKey1)));
            this.Write(" key1, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kKey2)));
            this.Write(" key2) => GetRowOrDefault(context, string.Empty, key1, key2);\n\n    [MethodImpl(Me" +
                    "thodImplOptions.AggressiveInlining)]\n    public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kValue)));
            this.Write(" GetRowOrDefault(DataTableContext context, string dataTableName, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kKey1)));
            this.Write(" key1, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kKey2)));
            this.Write(" key2)\n    {\n        var table = context.GetCached<DT");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.ClassName));
            this.Write(">(dataTableName);\n        return table != null ? table.Get(key1, key2)! : default" +
                    "!;\n    }\r\n\r\n    #endregion\r\n\r\n    #region MatrixDataRow Support\r\n\r\n    /// <summ" +
                    "ary>\r\n    /// 创建数据行实例\r\n    /// </summary>\r\n    protected override MatrixDataRowB" +
                    "ase<");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kKey1)));
            this.Write(", ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kKey2)));
            this.Write(", ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kValue)));
            this.Write("> CreateDataRowInstance()\r\n    {\r\n        return new DR");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.ClassName));
            this.Write("();\r\n    }\r\n\r\n    #endregion\r\n}\r\n\r\n/// <summary>\r\n/// ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.ClassName));
            this.Write(" 的数据行类 - 包含RowKey、ColumnKey和Value\r\n/// </summary>\r\npublic sealed class DR");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.ClassName));
            this.Write(" : MatrixDataRowBase<");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kKey1)));
            this.Write(", ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kKey2)));
            this.Write(", ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kValue)));
            this.Write(">\r\n{\r\n    /// <summary>\r\n    /// 构造函数\r\n    /// </summary>\r\n    public DR");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.ClassName));
            this.Write("() : base()\r\n    {\r\n    }\r\n\r\n    /// <summary>\r\n    /// 构造函数\r\n    /// </summary>\r" +
                    "\n    /// <param name=\"rowKey\">行键</param>\r\n    /// <param name=\"columnKey\">列键</pa" +
                    "ram>\r\n    /// <param name=\"value\">值</param>\r\n    public DR");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.ClassName));
            this.Write("(");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kKey1)));
            this.Write(" rowKey, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kKey2)));
            this.Write(" columnKey, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kValue)));
            this.Write(" value) \r\n        : base(rowKey, columnKey, value)\r\n    {\r\n    }\r\n\r\n    /// <summ" +
                    "ary>\r\n    /// 从二进制读取器反序列化\r\n    /// </summary>\r\n    public override bool Deserial" +
                    "ize(BinaryReader reader)\r\n    {\r\n        ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kKey1)));
            this.Write(" rowKey;\r\n        ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildDeserializeMethodString(kKey1).Replace(kKey1, "rowKey")));
            this.Write("\r\n\r\n        ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kKey2)));
            this.Write(" columnKey;\r\n        ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildDeserializeMethodString(kKey2).Replace(kKey2, "columnKey")));
            this.Write("\r\n\r\n        ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildTypeString(kValue)));
            this.Write(" value;\r\n        ");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildDeserializeMethodString(kValue).Replace(kValue, "value")));
            this.Write("\r\n\r\n        SetData(rowKey, columnKey, value);\r\n        return true;\r\n    }\r\n}\r\n\r" +
                    "\n");
 if (!string.IsNullOrEmpty(GenerationContext.Namespace)) {
            this.Write("\n}\n");
 }
            this.Write("\n");

    var normalizedMatrixOutput = GenerationEnvironment.ToString().TrimEnd('\r', '\n');
    GenerationEnvironment.Clear();
    Write(normalizedMatrixOutput);

            this.Write("\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class DataMatrixTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0)
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
