// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DataTables.GeneratorCore
{
    using System;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class DataTableTemplate : DataTableTemplateBase
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("// <auto-generated />\r\n#pragma warning disable CS0105\r\n#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring as nullable.\r\n#pragma warning disable CS8602 // Dereference of a possibly null reference.\r\n\r\nusing System;\r\nusing System.Collections.Generic;\r\nusing System.Collections.ObjectModel;\r\nusing System.IO;\r\nusing System.Linq;\r\nusing System.Runtime.CompilerServices;\r\nusing DataTables;");
 if (!string.IsNullOrEmpty(Using)) { 
            
            this.Write(this.ToStringHelper.ToStringWithCulture(Environment.NewLine + Using));
            
            #line default
            #line hidden
 } 
            this.Write("\r\n#nullable enable\r\n\r\n");
 if (!string.IsNullOrEmpty(Namespace)) { 
            this.Write("namespace ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
 } 
            this.Write("public sealed partial class ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataTableClassName));
            
            #line default
            #line hidden
            this.Write(" : DataTable<");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataRowClassName));
            
            #line default
            #line hidden
            this.Write(">\r\n{\r\n    public override ulong SchemaHash => ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(DataTableSchemaHash.Compute(GenerationContext)));
            
            #line default
            #line hidden
            this.Write("UL;\r\n");

    var dictIndex = 1;
    foreach (var index in GenerationContext.IndexDefinitions)
    {
        var dictionaryType = GenerationContext.BuildIndexDictDefine(index.Fields);

            this.Write("    private readonly ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(dictionaryType));
            
            #line default
            #line hidden
            this.Write(" m_Dict");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(dictIndex));
            
            #line default
            #line hidden
            this.Write(" = new ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(dictionaryType));
            
            #line default
            #line hidden
            this.Write("();\r\n    private readonly ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.BuildReadOnlyIndexDictDefine(index.Fields)));
            
            #line default
            #line hidden
            this.Write(" m_Index");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(dictIndex));
            
            #line default
            #line hidden
            this.Write(";\r\n");

        dictIndex++;
    }
    foreach (var group in GenerationContext.GroupIndexDefinitions)
    {
        var dictionaryType = GenerationContext.BuildGroupDictDefine(group.Fields);

            this.Write("    private readonly ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(dictionaryType));
            
            #line default
            #line hidden
            this.Write(" m_Dict");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(dictIndex));
            
            #line default
            #line hidden
            this.Write(" = new ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(dictionaryType));
            
            #line default
            #line hidden
            this.Write("();\r\n    private readonly ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.BuildReadOnlyGroupDictDefine(group.Fields)));
            
            #line default
            #line hidden
            this.Write(" m_Index");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(dictIndex));
            
            #line default
            #line hidden
            this.Write(";\r\n");

        dictIndex++;
    }

    if (dictIndex == 1)
    {

            this.Write("    public ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataTableClassName));
            
            #line default
            #line hidden
            this.Write("(string name, int capacity) : base(name, capacity) { }\r\n");

    }
    else
    {

            this.Write("    public ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataTableClassName));
            
            #line default
            #line hidden
            this.Write("(string name, int capacity) : base(name, capacity)\r\n    {\r\n");

        for (var i = 1; i < dictIndex; i++)
        {
            var dictionaryType = i <= GenerationContext.IndexDefinitions.Count
                ? GenerationContext.BuildIndexDictDefine(GenerationContext.IndexDefinitions[i - 1].Fields)
                : GenerationContext.BuildGroupDictDefine(GenerationContext.GroupIndexDefinitions[i - GenerationContext.IndexDefinitions.Count - 1].Fields);

            this.Write("        m_Index");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" = new ReadOnlyDictionary<");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(dictionaryType.Substring(11)));
            
            #line default
            #line hidden
            this.Write("(m_Dict");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(");\r\n");

        }

            this.Write("    }\r\n");

    }

            this.Write("\r\n    protected override void InternalAddDataRow(int index, ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataRowClassName));
            
            #line default
            #line hidden
            this.Write(" dataRow)\r\n    {\r\n        base.InternalAddDataRow(index, dataRow);\r\n\r\n");

    for (var i = 0; i < GenerationContext.IndexDefinitions.Count; i++)
    {
        var fields = GenerationContext.IndexDefinitions[i].Fields;
        var key = fields.Length > 1 ? "(" + string.Join(", ", fields.Select(x => $"dataRow.{x}")) + ")" : $"dataRow.{fields[0]}";

            this.Write("        m_Dict");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(i + 1));
            
            #line default
            #line hidden
            this.Write(".Add(");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(key));
            
            #line default
            #line hidden
            this.Write(", dataRow);\r\n");

    }
    for (var i = 0; i < GenerationContext.GroupIndexDefinitions.Count; i++)
    {
        var fields = GenerationContext.GroupIndexDefinitions[i].Fields;
        var dictNo = GenerationContext.IndexDefinitions.Count + i + 1;
        var key = fields.Length > 1 ? "(" + string.Join(", ", fields.Select(x => $"dataRow.{x}")) + ")" : $"dataRow.{fields[0]}";

            this.Write("        {\r\n            if (!m_Dict");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(dictNo));
            
            #line default
            #line hidden
            this.Write(".TryGetValue(");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(key));
            
            #line default
            #line hidden
            this.Write(", out var arr))\r\n            {\r\n                arr = new List<");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataRowClassName));
            
            #line default
            #line hidden
            this.Write(">();\r\n                m_Dict");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(dictNo));
            
            #line default
            #line hidden
            this.Write(".Add(");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(key));
            
            #line default
            #line hidden
            this.Write(", arr);\r\n            }\r\n            arr.Add(dataRow);\r\n        }\r\n");

    }

            this.Write("    }\r\n\r\n    #region Instance API\r\n");

    for (var i = 0; i < GenerationContext.IndexDefinitions.Count; i++)
    {
        var fields = GenerationContext.IndexDefinitions[i].Fields;
        var suffix = string.Join("And", fields);
        var key = fields.Length > 1 ? "(" + GenerationContext.BuildCamelCaseParameters(fields) + ")" : GenerationContext.ToCamelCase(fields[0]);

            this.Write("\r\n    [MethodImpl(MethodImplOptions.AggressiveInlining)]\r\n    public ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataRowClassName));
            
            #line default
            #line hidden
            this.Write("? GetDataRowBy");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(suffix));
            
            #line default
            #line hidden
            this.Write("(");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.BuildMethodParameters(fields)));
            
            #line default
            #line hidden
            this.Write(")\r\n    {\r\n        return m_Index");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(i + 1));
            
            #line default
            #line hidden
            this.Write(".TryGetValue(");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(key));
            
            #line default
            #line hidden
            this.Write(", out var result) ? result : null;\r\n    }\r\n");

    }
    for (var i = 0; i < GenerationContext.GroupIndexDefinitions.Count; i++)
    {
        var fields = GenerationContext.GroupIndexDefinitions[i].Fields;
        var suffix = string.Join("And", fields);
        var dictNo = GenerationContext.IndexDefinitions.Count + i + 1;
        var key = fields.Length > 1 ? "(" + GenerationContext.BuildCamelCaseParameters(fields) + ")" : GenerationContext.ToCamelCase(fields[0]);

            this.Write("\r\n    [MethodImpl(MethodImplOptions.AggressiveInlining)]\r\n    public List<");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataRowClassName));
            
            #line default
            #line hidden
            this.Write(">? GetDataRowsGroupBy");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(suffix));
            
            #line default
            #line hidden
            this.Write("(");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.BuildMethodParameters(fields)));
            
            #line default
            #line hidden
            this.Write(")\r\n    {\r\n        return m_Index");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(dictNo));
            
            #line default
            #line hidden
            this.Write(".TryGetValue(");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(key));
            
            #line default
            #line hidden
            this.Write(", out var result) ? result : null;\r\n    }\r\n");

    }

            this.Write("    #endregion\r\n\r\n    #region Static API\r\n");

    for (var i = 0; i < GenerationContext.IndexDefinitions.Count; i++)
    {
        var fields = GenerationContext.IndexDefinitions[i].Fields;
        var suffix = string.Join("And", fields);
        var parameters = GenerationContext.BuildMethodParameters(fields);
        var key = fields.Length > 1 ? "(" + GenerationContext.BuildCamelCaseParameters(fields) + ")" : GenerationContext.ToCamelCase(fields[0]);

            this.Write("\r\n    [MethodImpl(MethodImplOptions.AggressiveInlining)]\r\n    public static ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataRowClassName));
            
            #line default
            #line hidden
            this.Write("? GetBy");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(suffix));
            
            #line default
            #line hidden
            this.Write("(");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(parameters));
            
            #line default
            #line hidden
            this.Write(")\r\n    {\r\n        var table = DataTableManager.GetDataTableInternal<");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataTableClassName));
            
            #line default
            #line hidden
            this.Write(">();\r\n        return table?.m_Index");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(i + 1));
            
            #line default
            #line hidden
            this.Write(".TryGetValue(");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(key));
            
            #line default
            #line hidden
            this.Write(", out var result) == true ? result : null;\r\n    }\r\n\r\n    [MethodImpl(MethodImplOptions.AggressiveInlining)]\r\n    public static bool TryGetBy");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(suffix));
            
            #line default
            #line hidden
            this.Write("(");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(parameters));
            
            #line default
            #line hidden
            this.Write(", out ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataRowClassName));
            
            #line default
            #line hidden
            this.Write("? result)\r\n    {\r\n        var table = DataTableManager.GetDataTableInternal<");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataTableClassName));
            
            #line default
            #line hidden
            this.Write(">();\r\n        result = null;\r\n        return table != null && table.m_Index");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(i + 1));
            
            #line default
            #line hidden
            this.Write(".TryGetValue(");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(key));
            
            #line default
            #line hidden
            this.Write(", out result);\r\n    }\r\n\r\n    [MethodImpl(MethodImplOptions.AggressiveInlining)]\r\n    public static bool Contains");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(suffix));
            
            #line default
            #line hidden
            this.Write("(");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(parameters));
            
            #line default
            #line hidden
            this.Write(")\r\n    {\r\n        var table = DataTableManager.GetDataTableInternal<");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataTableClassName));
            
            #line default
            #line hidden
            this.Write(">();\r\n        return table?.m_Index");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(i + 1));
            
            #line default
            #line hidden
            this.Write(".ContainsKey(");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(key));
            
            #line default
            #line hidden
            this.Write(") == true;\r\n    }\r\n\r\n    [MethodImpl(MethodImplOptions.AggressiveInlining)]\r\n    public static ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataRowClassName));
            
            #line default
            #line hidden
            this.Write("? GetRowBy");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(suffix));
            
            #line default
            #line hidden
            this.Write("(");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(parameters));
            
            #line default
            #line hidden
            this.Write(") => GetBy");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(suffix));
            
            #line default
            #line hidden
            this.Write("(");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.BuildCamelCaseParameters(fields)));
            
            #line default
            #line hidden
            this.Write(");\r\n");

    }
    for (var i = 0; i < GenerationContext.GroupIndexDefinitions.Count; i++)
    {
        var fields = GenerationContext.GroupIndexDefinitions[i].Fields;
        var suffix = string.Join("And", fields);
        var parameters = GenerationContext.BuildMethodParameters(fields);
        var key = fields.Length > 1 ? "(" + GenerationContext.BuildCamelCaseParameters(fields) + ")" : GenerationContext.ToCamelCase(fields[0]);
        var dictNo = GenerationContext.IndexDefinitions.Count + i + 1;

            this.Write("\r\n    [MethodImpl(MethodImplOptions.AggressiveInlining)]\r\n    public static IReadOnlyList<");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataRowClassName));
            
            #line default
            #line hidden
            this.Write(">? GetManyBy");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(suffix));
            
            #line default
            #line hidden
            this.Write("(");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(parameters));
            
            #line default
            #line hidden
            this.Write(")\r\n    {\r\n        var table = DataTableManager.GetDataTableInternal<");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataTableClassName));
            
            #line default
            #line hidden
            this.Write(">();\r\n        return table?.m_Index");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(dictNo));
            
            #line default
            #line hidden
            this.Write(".TryGetValue(");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(key));
            
            #line default
            #line hidden
            this.Write(", out var result) == true ? result : null;\r\n    }\r\n\r\n    [MethodImpl(MethodImplOptions.AggressiveInlining)]\r\n    public static bool Contains");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(suffix));
            
            #line default
            #line hidden
            this.Write("(");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(parameters));
            
            #line default
            #line hidden
            this.Write(")\r\n    {\r\n        var table = DataTableManager.GetDataTableInternal<");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataTableClassName));
            
            #line default
            #line hidden
            this.Write(">();\r\n        return table?.m_Index");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(dictNo));
            
            #line default
            #line hidden
            this.Write(".ContainsKey(");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(key));
            
            #line default
            #line hidden
            this.Write(") == true;\r\n    }\r\n\r\n    [MethodImpl(MethodImplOptions.AggressiveInlining)]\r\n    public static List<");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataRowClassName));
            
            #line default
            #line hidden
            this.Write(">? GetRowsGroupBy");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(suffix));
            
            #line default
            #line hidden
            this.Write("(");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(parameters));
            
            #line default
            #line hidden
            this.Write(") => GetManyBy");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(suffix));
            
            #line default
            #line hidden
            this.Write("(");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.BuildCamelCaseParameters(fields)));
            
            #line default
            #line hidden
            this.Write(") as List<");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataRowClassName));
            
            #line default
            #line hidden
            this.Write(">;\r\n");

    }

            this.Write("    #endregion\r\n}\r\n\r\n/// <summary>");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildSummary(GenerationContext.Title)));
            
            #line default
            #line hidden
            this.Write("</summary>\r\npublic sealed partial class ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataRowClassName));
            
            #line default
            #line hidden
            this.Write(" : DataRowBase\r\n{\r\n");

    foreach (var item in GenerationContext.Fields.Where(x => !x.IsIgnore))
    {

            this.Write("\r\n    /// <summary>");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildSummary(item.Title)));
            
            #line default
            #line hidden
            this.Write("</summary>");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(string.IsNullOrEmpty(item.Note) ? string.Empty : Environment.NewLine + "    /// <remarks>" + BuildSummary(item.Note) + "</remarks>"));
            
            #line default
            #line hidden
            this.Write("\r\n    public ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GetPropertyTypeString(item)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" { get; private set; }\r\n");

    }

            this.Write("\r\n    public override bool Deserialize(BinaryReader reader)\r\n    {\r\n");

    foreach (var item in GenerationContext.Fields.Where(x => !x.IsIgnore))
    {

            this.Write("        ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GetDeserializeMethodString(item)));
            
            #line default
            #line hidden
            this.Write("\r\n");

    }

            this.Write("        return true;\r\n    }\r\n}\r\n");
 if (!string.IsNullOrEmpty(Namespace)) { 
            this.Write("}\r\n");
 } 
            return this.GenerationEnvironment.ToString();
        }
    }
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class DataTableTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
