namespace DataTables.GeneratorCore;

using System;
using System.Linq;
using System.Text;

public partial class DataTableTemplate
{
    public virtual string TransformText()
    {
        var sb = new StringBuilder();
        string nl = Environment.NewLine;
        void W(string text = "") => sb.Append(text);
        void WL(string text = "") => sb.Append(text).Append(nl);

        WL("// <auto-generated />");
        WL("#pragma warning disable CS0105");
        WL("#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring as nullable.");
        WL("#pragma warning disable CS8602 // Dereference of a possibly null reference.");
        WL();
        WL("using System;");
        WL("using System.Collections.Generic;");
        WL("using System.Collections.ObjectModel;");
        WL("using System.IO;");
        WL("using System.Linq;");
        WL("using System.Runtime.CompilerServices;");
        WL("using DataTables;");
        if (!string.IsNullOrEmpty(Using)) WL(Using);
        WL();
        WL("#nullable enable");
        WL();
        if (!string.IsNullOrEmpty(Namespace)) { WL($"namespace {Namespace}"); WL("{"); }
        WL($"public sealed partial class {GenerationContext.DataTableClassName} : DataTable<{GenerationContext.DataRowClassName}>");
        WL("{");
        WL($"    public override ulong SchemaHash => {DataTableSchemaHash.Compute(GenerationContext)}UL;");
        WL();
        var dictIndex = 1;
        foreach (var index in GenerationContext.IndexDefinitions)
        {
            WL($"    private readonly {GenerationContext.BuildIndexDictDefine(index.Fields)} m_Dict{dictIndex} = new {GenerationContext.BuildIndexDictDefine(index.Fields)}();");
            WL($"    private readonly {GenerationContext.BuildReadOnlyIndexDictDefine(index.Fields)} m_Index{dictIndex};");
            dictIndex++;
        }
        foreach (var group in GenerationContext.GroupIndexDefinitions)
        {
            WL($"    private readonly {GenerationContext.BuildGroupDictDefine(group.Fields)} m_Dict{dictIndex} = new {GenerationContext.BuildGroupDictDefine(group.Fields)}();");
            WL($"    private readonly {GenerationContext.BuildReadOnlyGroupDictDefine(group.Fields)} m_Index{dictIndex};");
            dictIndex++;
        }
        if (dictIndex > 1) WL();
        if (dictIndex == 1)
        {
            WL($"    public {GenerationContext.DataTableClassName}(string name, int capacity) : base(name, capacity) {{ }}");
        }
        else
        {
            WL($"    public {GenerationContext.DataTableClassName}(string name, int capacity) : base(name, capacity)");
            WL("    {");
            for (var i = 1; i < dictIndex; i++)
            {
                var dictionaryType = i <= GenerationContext.IndexDefinitions.Count
                    ? GenerationContext.BuildIndexDictDefine(GenerationContext.IndexDefinitions[i - 1].Fields)
                    : GenerationContext.BuildGroupDictDefine(GenerationContext.GroupIndexDefinitions[i - GenerationContext.IndexDefinitions.Count - 1].Fields);
                WL($"        m_Index{i} = new ReadOnlyDictionary<{dictionaryType.Substring(11)}(m_Dict{i});");
            }
            WL("    }");
        }
        WL();
        WL($"    protected override void InternalAddDataRow(int index, {GenerationContext.DataRowClassName} dataRow)");
        WL("    {");
        WL("        base.InternalAddDataRow(index, dataRow);");
        WL();
        for (var i = 0; i < GenerationContext.IndexDefinitions.Count; i++)
        {
            var fields = GenerationContext.IndexDefinitions[i].Fields;
            WL($"        m_Dict{i + 1}.Add({BuildDataRowKey(fields)}, dataRow);");
        }
        for (var i = 0; i < GenerationContext.GroupIndexDefinitions.Count; i++)
        {
            var fields = GenerationContext.GroupIndexDefinitions[i].Fields;
            var n = GenerationContext.IndexDefinitions.Count + i + 1;
            WL("        {");
            WL($"            if (!m_Dict{n}.TryGetValue({BuildDataRowKey(fields)}, out var arr))");
            WL("            {");
            WL($"                arr = new List<{GenerationContext.DataRowClassName}>();");
            WL($"                m_Dict{n}.Add({BuildDataRowKey(fields)}, arr);");
            WL("            }");
            WL("            arr.Add(dataRow);");
            WL("        }");
        }
        WL("    }");
        WL();
        WL("    #region Instance API");
        for (var i = 0; i < GenerationContext.IndexDefinitions.Count; i++) EmitUniqueApi(sb, GenerationContext.IndexDefinitions[i].Fields, i + 1, false);
        for (var i = 0; i < GenerationContext.GroupIndexDefinitions.Count; i++) EmitGroupApi(sb, GenerationContext.GroupIndexDefinitions[i].Fields, GenerationContext.IndexDefinitions.Count + i + 1, false);
        WL("    #endregion"); WL();
        WL("    #region Static API");
        for (var i = 0; i < GenerationContext.IndexDefinitions.Count; i++) EmitUniqueApi(sb, GenerationContext.IndexDefinitions[i].Fields, i + 1, true);
        for (var i = 0; i < GenerationContext.GroupIndexDefinitions.Count; i++) EmitGroupApi(sb, GenerationContext.GroupIndexDefinitions[i].Fields, GenerationContext.IndexDefinitions.Count + i + 1, true);
        WL("    #endregion");
        WL("}"); WL();
        WL($"/// <summary>{BuildSummary(GenerationContext.Title)}</summary>");
        WL($"public sealed partial class {GenerationContext.DataRowClassName} : DataRowBase");
        WL("{");
        foreach (var item in GenerationContext.Fields.Where(x => !x.IsIgnore))
        {
            WL(); WL($"    /// <summary>{BuildSummary(item.Title)}</summary>" + (string.IsNullOrEmpty(item.Note) ? string.Empty : nl + "    /// <remarks>" + BuildSummary(item.Note) + "</remarks>"));
            WL($"    public {GetPropertyTypeString(item)} {item.Name} {{ get; private set; }}");
        }
        WL(); WL("    public override bool Deserialize(BinaryReader reader)"); WL("    {");
        foreach (var item in GenerationContext.Fields.Where(x => !x.IsIgnore)) WL($"        {GetDeserializeMethodString(item)}");
        WL("        return true;"); WL("    }"); WL("}");
        if (!string.IsNullOrEmpty(Namespace)) WL("}");
        return sb.ToString();
    }

    private void EmitUniqueApi(StringBuilder sb, string[] fields, int dictNo, bool isStatic)
    {
        var row = GenerationContext.DataRowClassName;
        var suffix = string.Join("And", fields);
        var pars = GenerationContext.BuildMethodParameters(fields);
        var key = BuildParameterKey(fields);

        if (!isStatic)
        {
            sb.AppendLine();
            sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"    public {row}? GetDataRowBy{suffix}({pars})");
            sb.AppendLine("    {");
            sb.AppendLine($"        return m_Index{dictNo}.TryGetValue({key}, out var result) ? result : null;");
            sb.AppendLine("    }");
            return;
        }

        var tableLine = $"        var table = DataTableManager.GetDataTableInternal<{GenerationContext.DataTableClassName}>();\n";
        sb.AppendLine(); sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]"); sb.AppendLine($"    public static {row}? GetBy{suffix}({pars})"); sb.AppendLine("    {"); sb.Append(tableLine); sb.AppendLine($"        return table?.m_Index{dictNo}.TryGetValue({key}, out var result) == true ? result : null;"); sb.AppendLine("    }");
        sb.AppendLine(); sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]"); sb.AppendLine($"    public static bool TryGetBy{suffix}({pars}, out {row}? result)"); sb.AppendLine("    {"); sb.Append(tableLine); sb.AppendLine("        result = null;"); sb.AppendLine($"        return table != null && table.m_Index{dictNo}.TryGetValue({key}, out result);"); sb.AppendLine("    }");
        sb.AppendLine(); sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]"); sb.AppendLine($"    public static bool Contains{suffix}({pars})"); sb.AppendLine("    {"); sb.Append(tableLine); sb.AppendLine($"        return table?.m_Index{dictNo}.ContainsKey({key}) == true;"); sb.AppendLine("    }");
        sb.AppendLine(); sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]"); sb.AppendLine($"    public static {row}? GetRowBy{suffix}({pars}) => GetBy{suffix}({GenerationContext.BuildCamelCaseParameters(fields)});");
    }

    private void EmitGroupApi(StringBuilder sb, string[] fields, int dictNo, bool isStatic)
    {
        var row = GenerationContext.DataRowClassName;
        var suffix = string.Join("And", fields);
        var pars = GenerationContext.BuildMethodParameters(fields);
        var key = BuildParameterKey(fields);

        if (!isStatic)
        {
            sb.AppendLine();
            sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"    public List<{row}>? GetDataRowsGroupBy{suffix}({pars})");
            sb.AppendLine("    {");
            sb.AppendLine($"        return m_Index{dictNo}.TryGetValue({key}, out var result) ? result : null;");
            sb.AppendLine("    }");
            return;
        }

        var tableLine = $"        var table = DataTableManager.GetDataTableInternal<{GenerationContext.DataTableClassName}>();\n";
        sb.AppendLine(); sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]"); sb.AppendLine($"    public static IReadOnlyList<{row}>? GetManyBy{suffix}({pars})"); sb.AppendLine("    {"); sb.Append(tableLine); sb.AppendLine($"        return table?.m_Index{dictNo}.TryGetValue({key}, out var result) == true ? result : null;"); sb.AppendLine("    }");
        sb.AppendLine(); sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]"); sb.AppendLine($"    public static bool Contains{suffix}({pars})"); sb.AppendLine("    {"); sb.Append(tableLine); sb.AppendLine($"        return table?.m_Index{dictNo}.ContainsKey({key}) == true;"); sb.AppendLine("    }");
        sb.AppendLine(); sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]"); sb.AppendLine($"    public static List<{row}>? GetRowsGroupBy{suffix}({pars}) => GetManyBy{suffix}({GenerationContext.BuildCamelCaseParameters(fields)}) as List<{row}>;");
    }

    private static string BuildDataRowKey(string[] fields) => fields.Length > 1 ? "(" + string.Join(", ", fields.Select(x => $"dataRow.{x}")) + ")" : $"dataRow.{fields[0]}";
    private static string BuildParameterKey(string[] fields) => fields.Length > 1 ? "(" + GenerationContext.BuildCamelCaseParameters(fields) + ")" : GenerationContext.ToCamelCase(fields[0]);
}
