// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 17.0.0.0
//
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DataTables.GeneratorCore
{
    using System;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;

    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class DataTableTemplate : DataTableTemplateBase
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write(@"
// <auto-generated />
#pragma warning disable CS0105
#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring as nullable.
#pragma warning disable CS8602 // Dereference of a possibly null reference.

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Runtime.CompilerServices;
using DataTables;");
 if (!string.IsNullOrEmpty(Using)) {
            this.Write(this.ToStringHelper.ToStringWithCulture(Environment.NewLine + Using));
 }
            this.Write("\n\n#nullable enable\n\n");
 if (!string.IsNullOrEmpty(Namespace)) {
            this.Write("namespace ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            this.Write("\n{\n");
 }
            this.Write("public sealed partial class ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataTableClassName));
            this.Write(" : DataTable<");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataRowClassName));
            this.Write(">\n{\n    public override ulong SchemaHash => ");
            this.Write(this.ToStringHelper.ToStringWithCulture(DataTableSchemaHash.Compute(GenerationContext)));
            this.Write("UL;\n");

    var dictIndex = 1;
    foreach (var index in GenerationContext.IndexDefinitions)
    {
        var dictionaryType = GenerationContext.BuildIndexDictDefine(index.Fields);

            this.Write("\n    private readonly ");
            this.Write(this.ToStringHelper.ToStringWithCulture(dictionaryType));
            this.Write(" m_Dict");
            this.Write(this.ToStringHelper.ToStringWithCulture(dictIndex));
            this.Write(" = new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(dictionaryType));
            this.Write("();\n    private readonly ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.BuildReadOnlyIndexDictDefine(index.Fields)));
            this.Write(" m_Index");
            this.Write(this.ToStringHelper.ToStringWithCulture(dictIndex));
            this.Write(";\n");

        dictIndex++;
    }
    foreach (var group in GenerationContext.GroupIndexDefinitions)
    {
        var dictionaryType = GenerationContext.BuildGroupDictDefine(group.Fields);

            this.Write("\n    private readonly ");
            this.Write(this.ToStringHelper.ToStringWithCulture(dictionaryType));
            this.Write(" m_Dict");
            this.Write(this.ToStringHelper.ToStringWithCulture(dictIndex));
            this.Write(" = new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(dictionaryType));
            this.Write("();\n    private readonly ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.BuildReadOnlyGroupDictDefine(group.Fields)));
            this.Write(" m_Index");
            this.Write(this.ToStringHelper.ToStringWithCulture(dictIndex));
            this.Write(";\n");

        dictIndex++;
    }

    if (dictIndex == 1)
    {

            this.Write("\n    public ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataTableClassName));
            this.Write("(string name, int capacity) : base(name, capacity) { }\n");

    }
    else
    {

            this.Write("\n    public ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataTableClassName));
            this.Write("(string name, int capacity) : base(name, capacity)\n    {\n");

        for (var i = 1; i < dictIndex; i++)
        {
            var dictionaryType = i <= GenerationContext.IndexDefinitions.Count
                ? GenerationContext.BuildIndexDictDefine(GenerationContext.IndexDefinitions[i - 1].Fields)
                : GenerationContext.BuildGroupDictDefine(GenerationContext.GroupIndexDefinitions[i - GenerationContext.IndexDefinitions.Count - 1].Fields);

            this.Write("\n        m_Index");
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            this.Write(" = new ReadOnlyDictionary<");
            this.Write(this.ToStringHelper.ToStringWithCulture(dictionaryType.Substring(11)));
            this.Write("(m_Dict");
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            this.Write(");\n");

        }

            this.Write("\n    }\n");

    }

            this.Write("\n\n    protected override void InternalAddDataRow(int index, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataRowClassName));
            this.Write(" dataRow)\n    {\n        base.InternalAddDataRow(index, dataRow);\n\n");

    for (var i = 0; i < GenerationContext.IndexDefinitions.Count; i++)
    {
        var fields = GenerationContext.IndexDefinitions[i].Fields;
        var key = fields.Length > 1 ? "(" + string.Join(", ", fields.Select(x => $"dataRow.{x}")) + ")" : $"dataRow.{fields[0]}";

            this.Write("\n        m_Dict");
            this.Write(this.ToStringHelper.ToStringWithCulture(i + 1));
            this.Write(".Add(");
            this.Write(this.ToStringHelper.ToStringWithCulture(key));
            this.Write(", dataRow);\n");

    }
    for (var i = 0; i < GenerationContext.GroupIndexDefinitions.Count; i++)
    {
        var fields = GenerationContext.GroupIndexDefinitions[i].Fields;
        var dictNo = GenerationContext.IndexDefinitions.Count + i + 1;
        var key = fields.Length > 1 ? "(" + string.Join(", ", fields.Select(x => $"dataRow.{x}")) + ")" : $"dataRow.{fields[0]}";

            this.Write("\n        {\n            if (!m_Dict");
            this.Write(this.ToStringHelper.ToStringWithCulture(dictNo));
            this.Write(".TryGetValue(");
            this.Write(this.ToStringHelper.ToStringWithCulture(key));
            this.Write(", out var arr))\n            {\n                arr = new List<");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataRowClassName));
            this.Write(">();\n                m_Dict");
            this.Write(this.ToStringHelper.ToStringWithCulture(dictNo));
            this.Write(".Add(");
            this.Write(this.ToStringHelper.ToStringWithCulture(key));
            this.Write(", arr);\n            }\n            arr.Add(dataRow);\n        }\n");

    }

            this.Write("\n    }\n\n    protected override void OnDataRowsRemoved()\n    {\n");

    for (var i = 1; i < dictIndex; i++)
    {

            this.Write("\n        m_Dict");
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            this.Write(".Clear();\n");

    }

            this.Write("\n        OnGeneratedRowsRemoved();\n    }\n\n    partial void OnGeneratedRowsRemoved" +
                    "();\n\n    #region Instance API\n");

    for (var i = 0; i < GenerationContext.IndexDefinitions.Count; i++)
    {
        var fields = GenerationContext.IndexDefinitions[i].Fields;
        var suffix = string.Join("And", fields);
        var key = fields.Length > 1 ? "(" + GenerationContext.BuildCamelCaseParameters(fields) + ")" : GenerationContext.ToCamelCase(fields[0]);

            this.Write("\n\n    [MethodImpl(MethodImplOptions.AggressiveInlining)]\n    public ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataRowClassName));
            this.Write("? GetDataRowBy");
            this.Write(this.ToStringHelper.ToStringWithCulture(suffix));
            this.Write("(");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.BuildMethodParameters(fields)));
            this.Write(")\n    {\n        return m_Index");
            this.Write(this.ToStringHelper.ToStringWithCulture(i + 1));
            this.Write(".TryGetValue(");
            this.Write(this.ToStringHelper.ToStringWithCulture(key));
            this.Write(", out var result) ? result : null;\n    }\n");

    }
    for (var i = 0; i < GenerationContext.GroupIndexDefinitions.Count; i++)
    {
        var fields = GenerationContext.GroupIndexDefinitions[i].Fields;
        var suffix = string.Join("And", fields);
        var dictNo = GenerationContext.IndexDefinitions.Count + i + 1;
        var key = fields.Length > 1 ? "(" + GenerationContext.BuildCamelCaseParameters(fields) + ")" : GenerationContext.ToCamelCase(fields[0]);

            this.Write("\n\n    [MethodImpl(MethodImplOptions.AggressiveInlining)]\n    public List<");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataRowClassName));
            this.Write(">? GetDataRowsGroupBy");
            this.Write(this.ToStringHelper.ToStringWithCulture(suffix));
            this.Write("(");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.BuildMethodParameters(fields)));
            this.Write(")\n    {\n        return m_Index");
            this.Write(this.ToStringHelper.ToStringWithCulture(dictNo));
            this.Write(".TryGetValue(");
            this.Write(this.ToStringHelper.ToStringWithCulture(key));
            this.Write(", out var result) ? result : null;\n    }\n");

    }

            this.Write("\n    #endregion\n\n    #region Static API\n");

    for (var i = 0; i < GenerationContext.IndexDefinitions.Count; i++)
    {
        var fields = GenerationContext.IndexDefinitions[i].Fields;
        var suffix = string.Join("And", fields);
        var parameters = GenerationContext.BuildMethodParameters(fields);
        var arguments = GenerationContext.BuildCamelCaseParameters(fields);
        var key = fields.Length > 1 ? "(" + GenerationContext.BuildCamelCaseParameters(fields) + ")" : GenerationContext.ToCamelCase(fields[0]);
        var tableNameParameter = GetTableNameParameter(fields);

            this.Write("\n\n    [MethodImpl(MethodImplOptions.AggressiveInlining)]\n    public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataRowClassName));
            this.Write("? GetBy");
            this.Write(this.ToStringHelper.ToStringWithCulture(suffix));
            this.Write("(");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameters));
            this.Write(") => GetBy");
            this.Write(this.ToStringHelper.ToStringWithCulture(suffix));
            this.Write("(string.Empty, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(arguments));
            this.Write(");\n\n    [MethodImpl(MethodImplOptions.AggressiveInlining)]\n    public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataRowClassName));
            this.Write("? GetBy");
            this.Write(this.ToStringHelper.ToStringWithCulture(suffix));
            this.Write("(string ");
            this.Write(this.ToStringHelper.ToStringWithCulture(tableNameParameter));
            this.Write(", ");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameters));
            this.Write(")\n    {\n        var table = DataTableManager.GetCached<");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataTableClassName));
            this.Write(">(");
            this.Write(this.ToStringHelper.ToStringWithCulture(tableNameParameter));
            this.Write(");\n        return table?.m_Index");
            this.Write(this.ToStringHelper.ToStringWithCulture(i + 1));
            this.Write(".TryGetValue(");
            this.Write(this.ToStringHelper.ToStringWithCulture(key));
            this.Write(", out var result) == true ? result : null;\n    }\n\n    [MethodImpl(MethodImplOptio" +
                    "ns.AggressiveInlining)]\n    public static bool TryGetBy");
            this.Write(this.ToStringHelper.ToStringWithCulture(suffix));
            this.Write("(");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameters));
            this.Write(", out ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataRowClassName));
            this.Write("? result) => TryGetBy");
            this.Write(this.ToStringHelper.ToStringWithCulture(suffix));
            this.Write("(string.Empty, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(arguments));
            this.Write(", out result);\n\n    [MethodImpl(MethodImplOptions.AggressiveInlining)]\n    public" +
                    " static bool TryGetBy");
            this.Write(this.ToStringHelper.ToStringWithCulture(suffix));
            this.Write("(string ");
            this.Write(this.ToStringHelper.ToStringWithCulture(tableNameParameter));
            this.Write(", ");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameters));
            this.Write(", out ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataRowClassName));
            this.Write("? result)\n    {\n        var table = DataTableManager.GetCached<");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataTableClassName));
            this.Write(">(");
            this.Write(this.ToStringHelper.ToStringWithCulture(tableNameParameter));
            this.Write(");\n        result = null;\n        return table != null && table.m_Index");
            this.Write(this.ToStringHelper.ToStringWithCulture(i + 1));
            this.Write(".TryGetValue(");
            this.Write(this.ToStringHelper.ToStringWithCulture(key));
            this.Write(", out result);\n    }\n\n    [MethodImpl(MethodImplOptions.AggressiveInlining)]\n    " +
                    "public static bool Contains");
            this.Write(this.ToStringHelper.ToStringWithCulture(suffix));
            this.Write("(");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameters));
            this.Write(") => Contains");
            this.Write(this.ToStringHelper.ToStringWithCulture(suffix));
            this.Write("(string.Empty, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(arguments));
            this.Write(");\n\n    [MethodImpl(MethodImplOptions.AggressiveInlining)]\n    public static bool" +
                    " Contains");
            this.Write(this.ToStringHelper.ToStringWithCulture(suffix));
            this.Write("(string ");
            this.Write(this.ToStringHelper.ToStringWithCulture(tableNameParameter));
            this.Write(", ");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameters));
            this.Write(")\n    {\n        var table = DataTableManager.GetCached<");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataTableClassName));
            this.Write(">(");
            this.Write(this.ToStringHelper.ToStringWithCulture(tableNameParameter));
            this.Write(");\n        return table?.m_Index");
            this.Write(this.ToStringHelper.ToStringWithCulture(i + 1));
            this.Write(".ContainsKey(");
            this.Write(this.ToStringHelper.ToStringWithCulture(key));
            this.Write(") == true;\n    }\n");

    }
    for (var i = 0; i < GenerationContext.GroupIndexDefinitions.Count; i++)
    {
        var fields = GenerationContext.GroupIndexDefinitions[i].Fields;
        var suffix = string.Join("And", fields);
        var parameters = GenerationContext.BuildMethodParameters(fields);
        var arguments = GenerationContext.BuildCamelCaseParameters(fields);
        var key = fields.Length > 1 ? "(" + GenerationContext.BuildCamelCaseParameters(fields) + ")" : GenerationContext.ToCamelCase(fields[0]);
        var dictNo = GenerationContext.IndexDefinitions.Count + i + 1;
        var tableNameParameter = GetTableNameParameter(fields);

            this.Write("\n\n    [MethodImpl(MethodImplOptions.AggressiveInlining)]\n    public static IReadO" +
                    "nlyList<");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataRowClassName));
            this.Write(">? GetManyBy");
            this.Write(this.ToStringHelper.ToStringWithCulture(suffix));
            this.Write("(");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameters));
            this.Write(") => GetManyBy");
            this.Write(this.ToStringHelper.ToStringWithCulture(suffix));
            this.Write("(string.Empty, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(arguments));
            this.Write(");\n\n    [MethodImpl(MethodImplOptions.AggressiveInlining)]\n    public static IRea" +
                    "dOnlyList<");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataRowClassName));
            this.Write(">? GetManyBy");
            this.Write(this.ToStringHelper.ToStringWithCulture(suffix));
            this.Write("(string ");
            this.Write(this.ToStringHelper.ToStringWithCulture(tableNameParameter));
            this.Write(", ");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameters));
            this.Write(")\n    {\n        var table = DataTableManager.GetCached<");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataTableClassName));
            this.Write(">(");
            this.Write(this.ToStringHelper.ToStringWithCulture(tableNameParameter));
            this.Write(");\n        return table?.m_Index");
            this.Write(this.ToStringHelper.ToStringWithCulture(dictNo));
            this.Write(".TryGetValue(");
            this.Write(this.ToStringHelper.ToStringWithCulture(key));
            this.Write(", out var result) == true ? result : null;\n    }\n\n    [MethodImpl(MethodImplOptio" +
                    "ns.AggressiveInlining)]\n    public static bool Contains");
            this.Write(this.ToStringHelper.ToStringWithCulture(suffix));
            this.Write("(");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameters));
            this.Write(") => Contains");
            this.Write(this.ToStringHelper.ToStringWithCulture(suffix));
            this.Write("(string.Empty, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(arguments));
            this.Write(");\n\n    [MethodImpl(MethodImplOptions.AggressiveInlining)]\n    public static bool" +
                    " Contains");
            this.Write(this.ToStringHelper.ToStringWithCulture(suffix));
            this.Write("(string ");
            this.Write(this.ToStringHelper.ToStringWithCulture(tableNameParameter));
            this.Write(", ");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameters));
            this.Write(")\n    {\n        var table = DataTableManager.GetCached<");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataTableClassName));
            this.Write(">(");
            this.Write(this.ToStringHelper.ToStringWithCulture(tableNameParameter));
            this.Write(");\n        return table?.m_Index");
            this.Write(this.ToStringHelper.ToStringWithCulture(dictNo));
            this.Write(".ContainsKey(");
            this.Write(this.ToStringHelper.ToStringWithCulture(key));
            this.Write(") == true;\n    }\n");

    }

            this.Write("\n    #endregion\n}\n\n/// <summary>");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildSummary(GenerationContext.Title)));
            this.Write("</summary>\npublic sealed partial class ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataRowClassName));
            this.Write(" : DataRowBase\n{\n");

    foreach (var item in GenerationContext.Fields.Where(x => !x.IsIgnore))
    {

            this.Write("\n\n    /// <summary>");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildSummary(item.Title)));
            this.Write("</summary>");
            this.Write(this.ToStringHelper.ToStringWithCulture(string.IsNullOrEmpty(item.Note) ? string.Empty : Environment.NewLine + "    /// <remarks>" + BuildSummary(item.Note) + "</remarks>"));
            this.Write("\n    public ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GetPropertyTypeString(item)));
            this.Write(" ");
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            this.Write(" { get; private set; }\n");

    }

            this.Write("\n\n    public override bool Deserialize(BinaryReader reader)\n    {\n");

    foreach (var item in GenerationContext.Fields.Where(x => !x.IsIgnore))
    {

            this.Write("\n        ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GetDeserializeMethodString(item)));
            this.Write("\n");

    }

            this.Write("\n        return true;\n    }\n}\n");
 if (!string.IsNullOrEmpty(Namespace)) {
            this.Write("\n}\n");
 }
            return this.GenerationEnvironment.ToString();
        }
    }
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class DataTableTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0)
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
