// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DataTables.GeneratorCore
{
    using System;
    using System.Linq;
    using DataTables.GeneratorCore;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class KvTableTemplate : DataTableTemplate
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("// <auto-generated />\r\n#pragma warning disable CS0105\r\n#pragma warning disable CS8618\r\n#pragma warning disable CS8602\r\n\r\nusing System;\r\nusing System.Collections.Generic;\r\nusing System.IO;\r\nusing System.Runtime.CompilerServices;\r\nusing DataTables;");
 if (!string.IsNullOrEmpty(Using)) { 
            
            this.Write(this.ToStringHelper.ToStringWithCulture(Environment.NewLine + Using));
            
            #line default
            #line hidden
 } 
            this.Write("\r\n#nullable enable\r\n\r\n");
 if (!string.IsNullOrEmpty(Namespace)) { 
            this.Write("namespace ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
 } 
            this.Write("public sealed partial class ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataTableClassName));
            
            #line default
            #line hidden
            this.Write(" : DataTable<");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataRowClassName));
            
            #line default
            #line hidden
            this.Write(">\r\n{\r\n    public override ulong SchemaHash => ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(DataTableSchemaHash.Compute(GenerationContext)));
            
            #line default
            #line hidden
            this.Write("UL;\r\n    public ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataTableClassName));
            
            #line default
            #line hidden
            this.Write("(string name, int capacity) : base(name, capacity) { }\r\n\r\n");

    foreach (var item in GenerationContext.Fields.Where(x => !x.IsIgnore))
    {

            this.Write("    /// <summary>");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildSummary(item.Title)));
            
            #line default
            #line hidden
            this.Write("</summary>\r\n    public static ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GetPropertyTypeString(item)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" => DataTableManager.GetDataTableInternal<");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataTableClassName));
            
            #line default
            #line hidden
            this.Write(">()![0].");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n");

    }

            this.Write("    public bool TryGetValue<T>(string key, out T? value)\r\n    {\r\n        value = default;\r\n        if (Count == 0) return false;\r\n        var property = typeof(");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataRowClassName));
            
            #line default
            #line hidden
            this.Write(").GetProperty(key);\r\n        if (property == null || !typeof(T).IsAssignableFrom(property.PropertyType)) return false;\r\n        value = (T?)property.GetValue(this[0]);\r\n        return true;\r\n    }\r\n\r\n    public T GetValue<T>(string key)\r\n    {\r\n        if (TryGetValue<T>(key, out var value)) return value!;\r\n        throw new KeyNotFoundException(key);\r\n    }\r\n}\r\n\r\n/// <summary>");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildSummary(GenerationContext.Title)));
            
            #line default
            #line hidden
            this.Write("</summary>\r\npublic sealed partial class ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataRowClassName));
            
            #line default
            #line hidden
            this.Write(" : DataRowBase\r\n{\r\n");

    foreach (var item in GenerationContext.Fields.Where(x => !x.IsIgnore))
    {

            this.Write("    /// <summary>");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildSummary(item.Title)));
            
            #line default
            #line hidden
            this.Write("</summary>\r\n    public ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GetPropertyTypeString(item)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" { get; private set; }\r\n\r\n");

    }

            this.Write("    public override bool Deserialize(BinaryReader reader)\r\n    {\r\n");

    foreach (var item in GenerationContext.Fields.Where(x => !x.IsIgnore))
    {

            this.Write("        ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(GetDeserializeMethodString(item)));
            
            #line default
            #line hidden
            this.Write("\r\n");

    }

            this.Write("        return true;\r\n    }\r\n}\r\n");
 if (!string.IsNullOrEmpty(Namespace)) { 
            this.Write("}\r\n");
 } 
            return this.GenerationEnvironment.ToString();
        }

    public KvTableTemplate(GenerationContext context) : base(context)
    {
    }

    }
}
