namespace DataTables.GeneratorCore;

using System;
using System.Linq;
using System.Text;

public sealed class KvTableTemplate : DataTableTemplate
{
    public KvTableTemplate(GenerationContext context) : base(context) { }

    public override string TransformText()
    {
        var sb = new StringBuilder();
        string nl = Environment.NewLine;
        void WL(string text = "") => sb.Append(text).Append(nl);

        WL("// <auto-generated />");
        WL("#pragma warning disable CS0105");
        WL("#pragma warning disable CS8618");
        WL("#pragma warning disable CS8602");
        WL();
        WL("using System;");
        WL("using System.Collections.Generic;");
        WL("using System.IO;");
        WL("using System.Runtime.CompilerServices;");
        WL("using DataTables;");
        if (!string.IsNullOrEmpty(Using)) WL(Using);
        WL();
        WL("#nullable enable");
        WL();
        if (!string.IsNullOrEmpty(Namespace)) { WL($"namespace {Namespace}"); WL("{"); }

        WL($"public sealed partial class {GenerationContext.DataTableClassName} : DataTable<{GenerationContext.DataRowClassName}>");
        WL("{");
        WL($"    public override ulong SchemaHash => {DataTableSchemaHash.Compute(GenerationContext)}UL;");
        WL($"    public {GenerationContext.DataTableClassName}(string name, int capacity) : base(name, capacity) {{ }}");
        WL();
        foreach (var item in GenerationContext.Fields.Where(x => !x.IsIgnore))
        {
            WL($"    /// <summary>{BuildSummary(item.Title)}</summary>");
            WL($"    public static {GetPropertyTypeString(item)} {item.Name} => DataTableManager.GetDataTableInternal<{GenerationContext.DataTableClassName}>()![0].{item.Name};");
            WL();
        }
        WL("    public bool TryGetValue<T>(string key, out T? value)");
        WL("    {");
        WL("        value = default;");
        WL("        if (Count == 0) return false;");
        WL("        var property = typeof(" + GenerationContext.DataRowClassName + ").GetProperty(key);");
        WL("        if (property == null || !typeof(T).IsAssignableFrom(property.PropertyType)) return false;");
        WL("        value = (T?)property.GetValue(this[0]);");
        WL("        return true;");
        WL("    }");
        WL();
        WL("    public T GetValue<T>(string key)");
        WL("    {");
        WL("        if (TryGetValue<T>(key, out var value)) return value!;");
        WL("        throw new KeyNotFoundException(key);");
        WL("    }");
        WL("}");
        WL();
        WL($"/// <summary>{BuildSummary(GenerationContext.Title)}</summary>");
        WL($"public sealed partial class {GenerationContext.DataRowClassName} : DataRowBase");
        WL("{");
        foreach (var item in GenerationContext.Fields.Where(x => !x.IsIgnore))
        {
            WL();
            WL($"    /// <summary>{BuildSummary(item.Title)}</summary>");
            WL($"    public {GetPropertyTypeString(item)} {item.Name} {{ get; private set; }}");
        }
        WL();
        WL("    public override bool Deserialize(BinaryReader reader)");
        WL("    {");
        foreach (var item in GenerationContext.Fields.Where(x => !x.IsIgnore)) WL($"        {GetDeserializeMethodString(item)}");
        WL("        return true;");
        WL("    }");
        WL("}");
        if (!string.IsNullOrEmpty(Namespace)) WL("}");
        return sb.ToString();
    }
}
