// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 17.0.0.0
//
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DataTables.GeneratorCore
{
    using System;
    using System.Linq;
    using DataTables.GeneratorCore;

    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class KvTableTemplate : DataTableTemplate
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("// <auto-generated />\r\n#pragma warning disable CS0105\r\n#pragma warning disable CS" +
                    "8618\r\n#pragma warning disable CS8602\r\n\r\nusing System;\r\nusing System.Collections." +
                    "Generic;\r\nusing System.IO;\r\nusing System.Runtime.CompilerServices;\r\nusing DataTa" +
                    "bles;");
 if (!string.IsNullOrEmpty(Using)) {
            this.Write(this.ToStringHelper.ToStringWithCulture(Environment.NewLine + Using));
 }
            this.Write("\r\n#nullable enable\r\n\r\n");
 if (!string.IsNullOrEmpty(Namespace)) {
            this.Write("namespace ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            this.Write("\r\n{\r\n");
 }
            this.Write("public sealed partial class ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataTableClassName));
            this.Write(" : DataTable<");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataRowClassName));
            this.Write(">\r\n{\r\n    public override ulong SchemaHash => ");
            this.Write(this.ToStringHelper.ToStringWithCulture(DataTableSchemaHash.Compute(GenerationContext)));
            this.Write("UL;\r\n    public ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataTableClassName));
            this.Write("(string name, int capacity) : base(name, capacity) { }\r\n\r\n");

    foreach (var item in GenerationContext.Fields.Where(x => !x.IsIgnore))
    {

            this.Write("\n    /// <summary>");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildSummary(item.Title)));
            this.Write("</summary>\n    public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GetPropertyTypeString(item)));
            this.Write(" Get");
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            this.Write("(DataTableContext context) => Get");
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            this.Write("(context, string.Empty);\n\n    public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GetPropertyTypeString(item)));
            this.Write(" Get");
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            this.Write("(DataTableContext context, string dataTableName) => context.GetCached<");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataTableClassName));
            this.Write(">(dataTableName)![0].");
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            this.Write(";\n\n");

    }

            this.Write("    public bool TryGetValue<T>(string key, out T? value)\r\n    {\r\n        value = " +
                    "default;\r\n        if (Count == 0) return false;\r\n        var property = typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataRowClassName));
            this.Write(@").GetProperty(key);
        if (property == null || !typeof(T).IsAssignableFrom(property.PropertyType)) return false;
        value = (T?)property.GetValue(this[0]);
        return true;
    }

    public T GetValue<T>(string key)
    {
        if (TryGetValue<T>(key, out var value)) return value!;
        throw new KeyNotFoundException(key);
    }
}

/// <summary>");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildSummary(GenerationContext.Title)));
            this.Write("</summary>\r\npublic sealed partial class ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.DataRowClassName));
            this.Write(" : DataRowBase\r\n{\r\n");

    foreach (var item in GenerationContext.Fields.Where(x => !x.IsIgnore))
    {

            this.Write("    /// <summary>");
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildSummary(item.Title)));
            this.Write("</summary>\r\n    public ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GetPropertyTypeString(item)));
            this.Write(" ");
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            this.Write(" { get; private set; }\r\n\r\n");

    }

            this.Write("    public override bool Deserialize(BinaryReader reader)\r\n    {\r\n");

    foreach (var item in GenerationContext.Fields.Where(x => !x.IsIgnore))
    {

            this.Write("        ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GetDeserializeMethodString(item)));
            this.Write("\r\n");

    }

            this.Write("        return true;\r\n    }\r\n}\r\n");
 if (!string.IsNullOrEmpty(Namespace)) {
            this.Write("\n}\n");
 }
            this.Write("\n");

    var normalizedKvOutput = GenerationEnvironment.ToString().TrimEnd('\r', '\n');
    GenerationEnvironment.Clear();
    Write(normalizedKvOutput);

            this.Write("\n");
            return this.GenerationEnvironment.ToString();
        }
    }
}
