// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 17.0.0.0
//
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DataTables.GeneratorCore
{
    using System;
    using System.Linq;
    using System.Text;
    using DataTables.GeneratorCore;

    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class TreeTableTemplate : DataTableTemplate
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {

    GenerationEnvironment.Clear();
    var text = base.TransformText();
    GenerationEnvironment.Clear();
    var insert = BuildTreeApi();
    var idx = text.IndexOf("    #endregion\r\n}", StringComparison.Ordinal);
    if (idx < 0)
    {
        idx = text.IndexOf("    #endregion\n}", StringComparison.Ordinal);
    }
    Write(idx < 0 ? text : text.Insert(idx, insert));


    string BuildTreeApi()
    {
        var row = GenerationContext.DataRowClassName;
        var table = GenerationContext.DataTableClassName;
        var sb = new StringBuilder();
        void WL(string text = "") => sb.AppendLine(text);

        WL();
        WL("    #region Tree API");
        WL($"    public IReadOnlyList<{row}> GetRoots() => (IReadOnlyList<{row}>?)GetDataRowsGroupByParentId(string.Empty) ?? Array.Empty<{row}>();");
        WL();
        WL("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        WL($"    public IReadOnlyList<{row}>? GetChildren(string id) => GetDataRowsGroupByParentId(id);");
        WL();
        WL("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        WL($"    public {row}? GetParent(string id)");
        WL("    {");
        WL("        var node = GetDataRowById(id);");
        WL("        return node == null || string.IsNullOrEmpty(node.ParentId) ? null : GetDataRowById(node.ParentId);");
        WL("    }");
        WL();
        WL($"    public IEnumerable<{row}> TraverseDepthFirst(string id)");
        WL("    {");
        WL("        var root = GetDataRowById(id);");
        WL("        if (root == null) yield break;");
        WL("        var stack = new Stack<IEnumerator<" + row + ">>();");
        WL("        yield return root;");
        WL("        stack.Push((GetChildren(root.Id) ?? Array.Empty<" + row + ">()).Reverse().GetEnumerator());");
        WL("        while (stack.Count > 0)");
        WL("        {");
        WL("            var it = stack.Peek();");
        WL("            if (!it.MoveNext())");
        WL("            {");
        WL("                it.Dispose();");
        WL("                stack.Pop();");
        WL("                continue;");
        WL("            }");
        WL("            var current = it.Current;");
        WL("            yield return current;");
        WL("            stack.Push((GetChildren(current.Id) ?? Array.Empty<" + row + ">()).Reverse().GetEnumerator());");
        WL("        }");
        WL("    }");
        WL();
        WL($"    public static IReadOnlyList<{row}> GetRoots(DataTableContext context) => GetRoots(context, string.Empty);");
        WL($"    public static IReadOnlyList<{row}> GetRoots(DataTableContext context, string dataTableName) => context.GetCached<{table}>(dataTableName)?.GetRoots() ?? Array.Empty<{row}>();");
        WL($"    public static IReadOnlyList<{row}>? GetChildren(DataTableContext context, string id) => GetChildren(context, string.Empty, id);");
        WL($"    public static IReadOnlyList<{row}>? GetChildren(DataTableContext context, string dataTableName, string id) => context.GetCached<{table}>(dataTableName)?.GetChildren(id);");
        WL($"    public static {row}? GetParent(DataTableContext context, string id) => GetParent(context, string.Empty, id);");
        WL($"    public static {row}? GetParent(DataTableContext context, string dataTableName, string id) => context.GetCached<{table}>(dataTableName)?.GetParent(id);");
        WL($"    public static IEnumerable<{row}> TraverseDepthFirst(DataTableContext context, string id) => TraverseDepthFirst(context, string.Empty, id);");
        WL($"    public static IEnumerable<{row}> TraverseDepthFirst(DataTableContext context, string dataTableName, string id) => context.GetCached<{table}>(dataTableName)?.TraverseDepthFirst(id) ?? Array.Empty<{row}>();");
        WL("    #endregion");
        return sb.ToString();
    }

            this.Write("\n");

    var normalizedTreeOutput = GenerationEnvironment.ToString().TrimEnd('\r', '\n');
    GenerationEnvironment.Clear();
    Write(normalizedTreeOutput);

            this.Write("\n");
            return this.GenerationEnvironment.ToString();
        }
    }
}
