using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using DataTables.GeneratorCore;
using FluentAssertions;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;
using Xunit;

namespace DataTables.Tests;

public sealed class IncrementalManifestV2Tests
{
    [Fact]
    public async Task ManifestsFromDifferentAbsoluteRoots_ShouldBeByteIdenticalAndContainOnlyStableIds()
    {
        var first = CreatePaths("dt_incremental_first_");
        var second = CreatePaths("dt_incremental_second_");
        var firstWorkbook = Path.Combine(first.Input, "nested", "items.xlsx");
        Directory.CreateDirectory(Path.GetDirectoryName(firstWorkbook)!);
        await CreateWorkbookAsync(firstWorkbook);
        var secondWorkbook = Path.Combine(second.Input, "nested", "items.xlsx");
        Directory.CreateDirectory(Path.GetDirectoryName(secondWorkbook)!);
        File.Copy(firstWorkbook, secondWorkbook);

        (await GenerateAsync([first.Input], first.Code, first.Data)).Succeeded.Should().BeTrue();
        (await GenerateAsync([second.Input], second.Code, second.Data)).Succeeded.Should().BeTrue();
        var firstText = await File.ReadAllTextAsync(Path.Combine(first.Data, ".dtgen-manifest.json"));
        var secondText = await File.ReadAllTextAsync(Path.Combine(second.Data, ".dtgen-manifest.json"));

        secondText.Should().Be(firstText);
        using var document = JsonDocument.Parse(firstText);
        document.RootElement.GetProperty("Version").GetInt32().Should().Be(2);
        document.RootElement.GetProperty("Inputs").EnumerateObject().Select(property => property.Name)
            .Should().Equal("root-0/nested/items.xlsx");
        firstText.Should().NotContain(Path.GetFileName(first.Root));
        firstText.Should().NotContain(first.Code).And.NotContain(first.Data);
        firstText.Should().NotContain("CodeOutputDirectory").And.NotContain("DataOutputDirectory");
        var outputs = document.RootElement.GetProperty("Inputs").EnumerateObject().Single().Value.GetProperty("Outputs").EnumerateArray().ToArray();
        outputs.Select(output => output.GetProperty("Kind").GetString()).Should().BeEquivalentTo("code", "data");
        outputs.Should().OnlyContain(output => !Path.IsPathRooted(output.GetProperty("Path").GetString()!));
    }

    [Fact]
    public async Task CopiedInputsAndOutputs_ShouldHitIncrementalCacheAfterAbsoluteRootMigration()
    {
        var source = CreatePaths("dt_incremental_source_");
        await CreateWorkbookAsync(Path.Combine(source.Input, "items.xlsx"));
        (await GenerateAsync([source.Input], source.Code, source.Data)).Succeeded.Should().BeTrue();
        var target = CreatePaths("dt_incremental_target_");
        CopyDirectory(source.Input, target.Input);
        CopyDirectory(source.Code, target.Code);
        CopyDirectory(source.Data, target.Data);
        var logs = new List<string>();

        var result = await GenerateAsync([target.Input], target.Code, target.Data, forceOverwrite: false, logger: logs.Add);

        result.Succeeded.Should().BeTrue();
        result.SucceededCount.Should().Be(0);
        result.SkippedCount.Should().Be(1);
        logs.Should().Contain(message => message.Contains("Incremental scan: 0 changed, 1 unchanged", StringComparison.Ordinal));
        logs.Should().NotContain(message => message.Contains("Generate Excel File:", StringComparison.Ordinal));
    }

    [Fact]
    public async Task VersionOneManifest_ShouldInvalidateAndRegenerateAllInputs()
    {
        var paths = CreatePaths("dt_incremental_v1_");
        await CreateWorkbookAsync(Path.Combine(paths.Input, "items.xlsx"));
        (await GenerateAsync([paths.Input], paths.Code, paths.Data)).Succeeded.Should().BeTrue();
        var manifestPath = Path.Combine(paths.Data, ".dtgen-manifest.json");
        var versionTwo = await File.ReadAllTextAsync(manifestPath);
        var versionOne = versionTwo.Replace("\"Version\": 2", "\"Version\": 1", StringComparison.Ordinal);
        versionOne.Should().NotBe(versionTwo);
        await File.WriteAllTextAsync(manifestPath, versionOne);
        var logs = new List<string>();

        var result = await GenerateAsync([paths.Input], paths.Code, paths.Data, forceOverwrite: false, logger: logs.Add);

        result.Succeeded.Should().BeTrue();
        result.SucceededCount.Should().Be(0, "identical regenerated bytes are content-skipped after parsing");
        result.SkippedCount.Should().Be(1);
        logs.Should().Contain(message => message.Contains("manifest version changed", StringComparison.OrdinalIgnoreCase));
        logs.Should().Contain(message => message.Contains("Generate Excel File:", StringComparison.Ordinal));
    }

    [Fact]
    public async Task OverlappingInputRoots_ShouldBeOwnedByTheEarlierConfiguredRoot()
    {
        var paths = CreatePaths("dt_incremental_overlap_");
        var nestedRoot = Directory.CreateDirectory(Path.Combine(paths.Input, "nested")).FullName;
        await CreateWorkbookAsync(Path.Combine(nestedRoot, "items.xlsx"));

        var result = await GenerateAsync([paths.Input, nestedRoot], paths.Code, paths.Data);

        result.Succeeded.Should().BeTrue();
        result.SucceededCount.Should().Be(1);
        using var manifest = JsonDocument.Parse(await File.ReadAllTextAsync(Path.Combine(paths.Data, ".dtgen-manifest.json")));
        manifest.RootElement.GetProperty("Inputs").EnumerateObject().Select(property => property.Name)
            .Should().Equal("root-0/nested/items.xlsx");
    }

    [Fact]
    public async Task ChangingOutputDirectories_ShouldNotDeleteFilesFromThePreviousDirectories()
    {
        var paths = CreatePaths("dt_incremental_output_change_");
        await CreateWorkbookAsync(Path.Combine(paths.Input, "items.xlsx"));
        (await GenerateAsync([paths.Input], paths.Code, paths.Data)).Succeeded.Should().BeTrue();
        var oldCode = Path.Combine(paths.Code, "DRItem.cs");
        var oldData = Path.Combine(paths.Data, "DataTables.Tests.Incremental.DTItem.bytes");
        var newCode = Directory.CreateDirectory(Path.Combine(paths.Root, "new-code")).FullName;
        var newData = Directory.CreateDirectory(Path.Combine(paths.Root, "new-data")).FullName;

        var result = await GenerateAsync([paths.Input], newCode, newData, forceOverwrite: false);

        result.Succeeded.Should().BeTrue();
        File.Exists(oldCode).Should().BeTrue();
        File.Exists(oldData).Should().BeTrue();
        File.Exists(Path.Combine(newCode, "DRItem.cs")).Should().BeTrue();
        File.Exists(Path.Combine(newData, "DataTables.Tests.Incremental.DTItem.bytes")).Should().BeTrue();
    }

    private static Task<GenerationResult> GenerateAsync(
        string[] inputDirectories,
        string codeDirectory,
        string dataDirectory,
        bool forceOverwrite = true,
        Action<string>? logger = null)
    {
        return new DataTableGenerator().GenerateFile(
            inputDirectories: inputDirectories,
            searchPatterns: ["*.xlsx"],
            codeOutputDir: codeDirectory,
            dataOutputDir: dataDirectory,
            usingNamespace: "DataTables.Tests.Incremental",
            dataRowClassPrefix: "DR",
            importNamespaces: string.Empty,
            filterColumnTags: string.Empty,
            forceOverwrite: forceOverwrite,
            logger: logger ?? (_ => { }));
    }

    private static async Task CreateWorkbookAsync(string path)
    {
        using var workbook = new XSSFWorkbook();
        var sheet = workbook.CreateSheet("Items");
        sheet.CreateRow(0).CreateCell(0, CellType.String).SetCellValue("dtgen=table, class=Item");
        sheet.CreateRow(1).CreateCell(0, CellType.String).SetCellValue("Identifier");
        sheet.CreateRow(2).CreateCell(0, CellType.String).SetCellValue("Id");
        sheet.CreateRow(3).CreateCell(0, CellType.String).SetCellValue("int");
        sheet.CreateRow(4).CreateCell(0, CellType.Numeric).SetCellValue(1);
        await using var stream = File.Create(path);
        workbook.Write(stream);
    }

    private static void CopyDirectory(string source, string destination)
    {
        foreach (var directory in Directory.EnumerateDirectories(source, "*", SearchOption.AllDirectories))
        {
            Directory.CreateDirectory(Path.Combine(destination, Path.GetRelativePath(source, directory)));
        }

        foreach (var file in Directory.EnumerateFiles(source, "*", SearchOption.AllDirectories))
        {
            var destinationFile = Path.Combine(destination, Path.GetRelativePath(source, file));
            Directory.CreateDirectory(Path.GetDirectoryName(destinationFile)!);
            File.Copy(file, destinationFile, overwrite: true);
        }
    }

    private static TestPaths CreatePaths(string prefix)
    {
        var root = Path.Combine(Path.GetTempPath(), prefix + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(root);
        return new TestPaths(
            root,
            Directory.CreateDirectory(Path.Combine(root, "input")).FullName,
            Directory.CreateDirectory(Path.Combine(root, "code")).FullName,
            Directory.CreateDirectory(Path.Combine(root, "data")).FullName);
    }

    private sealed record TestPaths(string Root, string Input, string Code, string Data);
}
