name: Build-Debug

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ChronosGames/Actions/.github/actions/setup-dotnet@main
      - run: dotnet build -c Debug
      - run: dotnet test -c Debug --no-build

  build-unity:
    if: ${{ ((github.event_name == 'push' && github.repository_owner == 'ChronosGames') || startsWith(github.event.pull_request.head.label, 'ChronosGames:')) && github.triggering_actor != 'dependabot[bot]' }}
    strategy:
      fail-fast: false
      matrix:
        unity: ["2022.3.39f1", "6000.0.12f1"] # Test with LTS
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Load secrets
        id: op-load-secret
        uses: 1password/load-secrets-action@v2
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN_PUBLIC }}
          UNITY_EMAIL: "op://GitHubActionsPublic/UNITY_LICENSE/username"
          UNITY_PASSWORD: "op://GitHubActionsPublic/UNITY_LICENSE/credential"
          UNITY_SERIAL: "op://GitHubActionsPublic/UNITY_LICENSE/serial"

      - uses: actions/checkout@v4

      # Run SourceGenerater to generate serialization code
      - uses: ChronosGames/Actions/.github/actions/setup-dotnet@main
      - run: dotnet build -c Debug # require build before run
      - name: Make sure generated files are exists.
        run: ls -lR "src/DataTables/bin/Debug/netstandard2.1"

      # Execute Unittest
      # /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath . -executeMethod UnitTestBuilder.BuildUnitTest /headless /ScriptBackend IL2CPP /BuildTarget StandaloneLinux64
      - name: Build UnitTest
        uses: ChronosGames/Actions/.github/actions/unity-builder@main
        env:
          UNITY_EMAIL: ${{ steps.op-load-secret.outputs.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ steps.op-load-secret.outputs.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ steps.op-load-secret.outputs.UNITY_SERIAL }}
        with:
          projectPath: src/DataTables.Unity
          unityVersion: ${{ matrix.unity }}
          targetPlatform: StandaloneLinux64
          buildMethod: UnitTestBuilder.BuildUnitTest
          customParameters: "/headless /ScriptBackend IL2CPP"
      - name: Check UnitTest file is generated
        run: ls -lR ./src/DataTables.Unity/bin/UnitTest
      - name: Execute UnitTest
        run: ./src/DataTables.Unity/bin/UnitTest/StandaloneLinux64_IL2CPP/test

      - uses: ChronosGames/Actions/.github/actions/check-metas@main # check meta files
        with:
          directory: src/DataTables.Unity
